services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/margins-app  
      - /margins-app/node_modules
    working_dir: /margins-app
    command: ["npm", "run", "dev"]
